Added logs for build file

diff --git a/deployments/Jenkinsfile b/deployments/Jenkinsfile
--- a/deployments/Jenkinsfile
+++ b/deployments/Jenkinsfile
@@ -38,37 +38,38 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 script {
-                    dir('server/weather-cache-service') {
-                        sh """
-                        docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG} .
-                        """
-                    }
-                }
-            }
-        }
-
-        stage('Login to Amazon ECR') {
-            steps {
-                script {
-                    // Login to AWS ECR (requires AWS CLI configured with IAM permissions)
                     sh """
-                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+                    if [ ! -f target/weather-cache-service.jar ]; then
+                        echo "ERROR: JAR file not found in target directory!"
+                        exit 1
+                    fi
+                    docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG} .
                     """
                 }
             }
         }
+        // stage('Login to Amazon ECR') {
+        //     steps {
+        //         script {
+        //             // Login to AWS ECR (requires AWS CLI configured with IAM permissions)
+        //             sh """
+        //             aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+        //             """
+        //         }
+        //     }
+        // }
 
-        stage('Push to ECR') {
-            steps {
-                script {
-                    // Push the Docker image to ECR
-                    sh """
-                    docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
-                    docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
-                    """
-                }
-            }
-        }
+        // stage('Push to ECR') {
+        //     steps {
+        //         script {
+        //             // Push the Docker image to ECR
+        //             sh """
+        //             docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
+        //             docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
+        //             """
+        //         }
+        //     }
+        // }
 
         // stage('Deploy to ECS') {
         //     steps {
